### ISSUE TITLE
Adding Show Number of List of Entries Displayed

### ISSUE THREAD

**Issue by Vichondrias1** [joaquimnetocel/svelte-datatables-net#2]
good day,
 can you add something like this sir? 
 it display the number of entries being display, depending on how many is being displayed in dataTable.
 
 example
![image](https://github.com/joaquimnetocel/svelte-datatables-net/assets/39474726/19aad5c2-c93d-48e4-87e7-b5a5281141c2)

**Comment by joaquimnetocel** [comment]
It is possible to do this in newer versions (dedicated to svelte 5). Take a look at the examples in the `routes` folder and you will see how to do it.
