### ISSUE TITLE
None of the REPL examples work

### ISSUE THREAD

**Issue by webJose** [joaquimnetocel/svelte-datatables-net#3]
They all throw this error:  `Unexpected character '@' (Datatable.svelte:35:1)`

**Comment by joaquimnetocel** [comment]
That is because svelte 5 was not released yet. The svelte REPL is using svelte 4.

If you want to see the REPL working, copy the REPL code to https://svelte-5-preview.vercel.app/ and everything will work.

Since version 1.0.0, the package works only with Svelte 5 and the REPL still uses Svelte 4.

**Comment by webJose** [comment]
Thanks.  Then why not provide the links to the v5 REPL directly?

**Comment by joaquimnetocel** [comment]
Because there is no way to save and share the code in the svelte 5 repl.

**Comment by webJose** [comment]
There's no need to save.  The URL contains the code in base64.  Complete the code, then copy the URL.

**Comment by joaquimnetocel** [comment]
Oh, I will try it later...

**Comment by joaquimnetocel** [comment]
Thanks for your tip! Problem solved now. The REPL links were updated and are working fine now!
